name: Test on Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_15.4.app
        xcodebuild -version

    - name: Build and Test
      run: |
        xcodebuild test \
          -project PokeApp.xcodeproj \
          -scheme PokeApp \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4' \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult 